<<<<<<< HEAD:.github/workflows/synk.yml
# This file describes the workflow to capture vunlerabilities via Snyk.

# It contains 3 jobs, "build", "security-sarif-reporting" and "security-monitor-reporting"

name: "Snyk"
=======
# # This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
# # testing change

# name: Node.js CI
>>>>>>> 2ae2a881288dbf58ad1fc9ee2e2f17f0a1f0741d:.github/workflows/node.js.yml

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

<<<<<<< HEAD:.github/workflows/synk.yml
jobs:
  ### Builds the code and runs the tests
  build: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
    - run: npm test

  ### Runs Snyk GitHub actions to scan code for vulnerabilities. If vulnerabilities are found, the job uploads a SARIF file containing the results to GitHub Code Scanning.
  security-sarif-reporting: 
    permissions:
      contents: write # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: write # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: efd72020-b3a1-49b8-b6b2-bbe83b725b27
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

  ### Runs the Snyk GitHub action with the monitor command. This command updates the Snyk UI with the latest vulnerability information for your project
  security-monitor-reporting:
    permissions:
      contents: write # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: write # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk with monitoring to update UI
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: efd72020-b3a1-49b8-b6b2-bbe83b725b27
        with:
          command: monitor
=======
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [14.x, 16.x, 18.x]
#         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
#     steps:
#     - uses: actions/checkout@v3
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v3
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#     - run: npm install
#     - run: npm run build --if-present
#     - run: npm test

#   security-sarif-reporting:
#     permissions:
#       contents: write # for actions/checkout to fetch code
#       security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
#       actions: write # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@master
#       - name: Run Snyk to check for vulnerabilities
#         uses: snyk/actions/node@master
#         continue-on-error: true
#         env:
#           SNYK_TOKEN: efd72020-b3a1-49b8-b6b2-bbe83b725b27
#         with:
#           args: --sarif-file-output=snyk.sarif
#       - name: Upload result to GitHub Code Scanning
#         uses: github/codeql-action/upload-sarif@v2
#         with:
#           sarif_file: snyk.sarif

#   security-monitor-reporting:
#     permissions:
#       contents: write # for actions/checkout to fetch code
#       security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
#       actions: write # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@master
#       - name: Run Snyk with monitoring to update UI
#         uses: snyk/actions/node@master
#         continue-on-error: true
#         env:
#           SNYK_TOKEN: efd72020-b3a1-49b8-b6b2-bbe83b725b27
#         with:
#           command: monitor
>>>>>>> 2ae2a881288dbf58ad1fc9ee2e2f17f0a1f0741d:.github/workflows/node.js.yml

